// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxexmozarqlvfexqajvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZXhtb3phcnFsdmZleHFhanZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTQ4OTYsImV4cCI6MjA2OTM3MDg5Nn0.H7HwvxJ-8dYb55YJ-mKXbj-z6_H7mKAaT2fUbLC2U9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});